# Generated by Django 2.1.5 on 2019-12-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='base', upload_to='img'),
            preserve_default=False,
        ),
    ]
